### ISSUE TITLE
Error on M1 MacBook Pro when moving focus to another application

### ISSUE THREAD

**Issue by andyearnshaw** [jaredly/vscode-background-terminal-notifier#10]
I recently got an updated work machine and it's got an M1 processor in it. Since I set up VSCode and transferred all my settings and extensions across, I've started getting the following error in VSCode's notification area:

```
Error while listening for process end: Error: Command failed: ps -o tty -1 ps: illegal option -- 1 usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]] [-g grp[,grp...]] [-u [uid,uid...]] [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]] ps [-L] ,ps: illegal option -- 1 usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]] [-g grp[,grp...]] [-u [uid,uid...]] [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]] ps [-L]
```

![image](https://user-images.githubusercontent.com/1826067/235145796-493c2cf1-3636-4239-aa77-06326889b8a2.png)

The extension still works despite this error, but the error notification itself is very obtrusive. If I have long-running tasks I just end up leaving the notification there as it will just pop back up again when I shift focus to my browser or another application.

**Comment by ryanparker-st** [comment]
This seems to have returned.
